# Generated by Django 3.0.6 on 2020-06-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0002_laptop_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='reviews',
            field=models.IntegerField(default=3, max_length=1),
        ),
    ]
