# Generated by Django 3.0.6 on 2020-06-06 06:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0005_auto_20200606_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='reviews',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
