# Generated by Django 3.0.6 on 2020-06-09 10:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0006_auto_20200606_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.AlterField(
            model_name='laptop',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
