# Generated by Django 3.0.6 on 2020-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
