# Generated by Django 3.0.6 on 2020-06-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0009_cart_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Laptop_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Electronics.Laptop'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Mobile_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Electronics.Mobile'),
        ),
    ]
