# Generated by Django 3.0.6 on 2020-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0010_auto_20200613_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='small_desc',
            field=models.CharField(blank=True, default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='mobile',
            name='small_desc',
            field=models.CharField(blank=True, default='none', max_length=250),
        ),
    ]
