# Generated by Django 3.0.6 on 2020-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0011_auto_20200613_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='small_desc',
            field=models.TextField(blank=True, default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='small_desc',
            field=models.TextField(blank=True, default='none', max_length=500),
        ),
    ]
