# Generated by Django 3.0.6 on 2020-06-14 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Electronics', '0012_auto_20200613_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('product_name', models.CharField(max_length=50)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
