# Generated by Django 3.0.6 on 2020-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0016_auto_20200614_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Recieve',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('amount_receive', models.IntegerField()),
                ('Currency', models.CharField(max_length=10)),
                ('GatewayName', models.CharField(max_length=10)),
                ('Respmsg', models.CharField(max_length=10)),
                ('respcode', models.CharField(max_length=10)),
                ('Txnid', models.IntegerField()),
                ('txnamount', models.IntegerField()),
                ('Status', models.CharField(max_length=10)),
                ('BANKTXNID', models.CharField(max_length=10)),
                ('TXNDATE', models.CharField(max_length=100)),
            ],
        ),
    ]
