# Generated by Django 3.0.6 on 2020-06-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0017_order_recieve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_recieve',
            name='amount_receive',
        ),
    ]
