# Generated by Django 3.0.6 on 2020-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0018_remove_order_recieve_amount_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_recieve',
            name='Bankname',
            field=models.CharField(default='Payment', max_length=50),
            preserve_default=False,
        ),
    ]
