# Generated by Django 3.0.6 on 2020-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0020_order_recieve_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_recieve',
            name='txnamount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
