# Generated by Django 3.0.6 on 2020-06-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0021_auto_20200615_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_recieve',
            name='Txnid',
            field=models.CharField(max_length=1000),
        ),
    ]
