# Generated by Django 3.0.6 on 2020-07-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0022_auto_20200615_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mobile',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
