# Generated by Django 3.0.6 on 2020-07-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0023_auto_20200709_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
